apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app-name: pod-1
    purpose: pod-affinity
spec:
  containers:
  - name: pod-1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app-name: pod-2
    purpose: pod-anti-affinity
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # this is hard anti-affinity
      - labelSelector:
          matchExpressions:
          - key: app-name
            operator: In #NotIn # Anti-affinity condition pod-1 & pod-2 should not be assigned to the same Node
            values:
            - pod-1
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: pod-2
    image: nginx